### ISSUE TITLE
crash / panic - scraper_rpi2.zip

### ISSUE THREAD

**Issue by jpereira** [sselph/scraper#114]
``````
# uname -a
Linux RECALBOX 4.1.19-v7 #1 SMP Fri Aug 12 10:56:53 UTC 2016 armv7l GNU/Linux
# cd /recalbox/share/roms/snes
# /recalbox/share/temp/scraper -scrape_all -thumb_only
2016/10/25 21:59:38 INFO: Checking for new hash.csv.
2016/10/25 21:59:38 INFO: hash.csv "e2315a44c3d4c5d200477a109e079f29" up to date.
2016/10/25 21:59:57 INFO: Checking for new MAME History.
2016/10/25 21:59:57 INFO: Upgrading MAME History:  -> "d1ab8d1b85b3bc455b6f72ec1366b40c".
2016/10/25 22:00:01 INFO: Upgrade Complete.
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x43fb60, 0x10920030)
    /usr/local/go/src/runtime/panic.go:500 +0x33c
main.getSystems(0x0, 0x0, 0x0, 0x0, 0x0)
    /home/sselph/go/src/github.com/sselph/scraper/scraper.go:510 +0x6bc
main.main()
    /home/sselph/go/src/github.com/sselph/scraper/scraper.go:658 +0x1754
# ```
``````

**Comment by sselph** [comment]
Sorry, I haven't been active much lately. I need to add a fix to throw a useful error but this is because the es_systems.cfg file is malformed. `-scrape_all` reads this file then iterates over all the systems. Your file was parsed but was missing the list of systems.
