### ISSUE TITLE
Panic scraping MAME 2003 Roms

### ISSUE THREAD

**Issue by medoro** [sselph/scraper#127]
I have this error. Windows 10 Pro.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x14 pc=0x408fe7]

goroutine 22 [running]:
panic(0x7e9580, 0x111fe030)
        /usr/local/go/src/runtime/panic.go:500 +0x331
main.crawlROMs.func2(0x11354fa0, 0x113582c0, 0x0, 0x11354d50, 0x11353620, 0x11336460)
        /home/sselph/go/src/github.com/sselph/scraper/scraper.go:295 +0x527
created by main.crawlROMs
        /home/sselph/go/src/github.com/sselph/scraper/scraper.go:328 +0xbd7
```

**Comment by sselph** [comment]
What was the command you used? It looks like it had a `-missing` flag? I think I'm not handling something properly there. If you leave that off it should not crash but I can hopefully have a fix for the issue tonight.

**Comment by sselph** [comment]
I think this fixes it but let me know if it doesn't.
