### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by cr4nk89** [sselph/scraper#135]
I get an error on osx while scraping n64 roms. Don't know why its on n64. Other systems work. Latest  version and did about 270roms until it errors.

```
panic: runtime error: index out of range
goroutine 230 [running]:
panic(0x428dc0, 0xc42000e0a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/sselph/scraper/rom/hash.zSwap(0xc420394000, 0xad846, 0x100000)
	/home/sselph/go/src/github.com/sselph/scraper/rom/hash/hash.go:191 +0x73
github.com/sselph/scraper/rom/hash.swapReader.Read(0x68cb40, 0xc42013e098, 0xc4216c39d0, 0x4, 0x4, 0xc4216c39c8, 0x4dae20, 0xc420394000, 0x100000, 0x100000, ...)
	/home/sselph/go/src/github.com/sselph/scraper/rom/hash/hash.go:234 +0x371
github.com/sselph/scraper/rom/hash.(*swapReader).Read(0xc420ecb280, 0xc420394000, 0x100000, 0x100000, 0x100000, 0x0, 0x0)
	<autogenerated>:1 +0x99
github.com/sselph/scraper/rom/hash.Hash(0xc420dd07e0, 0x30, 0x68f740, 0xc420132310, 0xc420394000, 0x100000, 0x100000, 0x0, 0x0, 0x0, ...)
	/home/sselph/go/src/github.com/sselph/scraper/rom/hash/hash.go:384 +0xef
github.com/sselph/scraper/ds.(*Hasher).Hash(0xc420146060, 0xc420dd07e0, 0x30, 0x0, 0x0, 0x0, 0x0)
	/home/sselph/go/src/github.com/sselph/scraper/ds/hasher.go:43 +0x52a
github.com/sselph/scraper/ds.(*SS).GetName(0xc420128370, 0xc420dd07e0, 0x30, 0x100, 0x55)
	/home/sselph/go/src/github.com/sselph/scraper/ds/ss.go:127 +0x47
github.com/sselph/scraper/rom.(*ROM).GetGame(0xc420d4a280, 0xc420ec7e00, 0x1, 0x1, 0xc420152b30, 0x0, 0x0)
	/home/sselph/go/src/github.com/sselph/scraper/rom/rom.go:214 +0x12b
main.worker(0xc420ec7e00, 0x1, 0x1, 0xc42016ac80, 0xc420152b30, 0xc42083d620, 0xc42083d6e0, 0xc420ec7e20)
	/home/sselph/go/src/github.com/sselph/scraper/scraper.go:127 +0x2ca
created by main.crawlROMs
	/home/sselph/go/src/github.com/sselph/scraper/scraper.go:269 +0x7a1 
```

**Comment by cr4nk89** [comment]
LaC's MOD Player - The Temple Gates (PD).z64 
Caused the problem. Removed the rom and everything works fine. Not sure if the name or the file crashed the scraper.

**Comment by sselph** [comment]
Yeah the issue is I'm not properly handling when a n64 rom is an odd size. The roms should be in increments of 4 bytes but this one isn't. So when I reference a byte that doesn't exist it panics. I'll get a fix out tonight so it won't panic.

**Comment by sselph** [comment]
Actually if it is possible, can you tell me the size of that file in bytes? I want to duplicate it so I know when it should be working.

**Comment by cr4nk89** [comment]
Size: 2.807.878 Byte
Uploaded the file as well for testing reasons:
http://www.file-upload.net/download-12284278/LaCsMODPlayer-TheTempleGatesPD.z64.html
Don't even know what kind of rom it is. Never played it. I however thought it would help improving your scraper when I report the error.
